# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Jfs_A8Bm0irOXuCRyI16uKMmufp5W_l
"""

import pandas as pd
import numpy as np
import streamlit as st
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

# Título de la aplicación
st.write("¿Estás en forma?")
st.image("fit.jpg", caption="Clasificación de condición física", use_container_width=True)
st.header("Ingresa tus datos")

# Función para cargar y limpiar los datos
def load_data():
    df = pd.read_csv('Fitness_Classification.csv', encoding='latin-1')

    # Limpiar columna 'smokes' (valores mixtos: 0, 1, 'yes', 'no')
    df['smokes'] = df['smokes'].astype(str).str.lower()
    df['smokes'] = df['smokes'].map({'0': 0, '1': 1, 'no': 0, 'yes': 1, 'sí': 1, 'si': 1}).fillna(0)

    # Codificar 'gender': F → 1, M → 0
    df['gender'] = df['gender'].map({'F': 1, 'M': 0})

    # Eliminar filas sin etiqueta
    df = df.dropna(subset=['is_fit'])

    # Rellenar NaN en columnas numéricas con la mediana
    num_cols = df.select_dtypes(include=[np.number]).columns
    for col in num_cols:
        df[col] = df[col].fillna(df[col].median())

    return df

# Cargar datos y entrenar modelo
datos = load_data()
X = datos.drop(columns=['is_fit'])
y = datos['is_fit']

modelo = DecisionTreeClassifier(random_state=1613318)
modelo.fit(X, y)

# Entrada del usuario
def user_input():
    age = st.number_input('Edad', min_value=15, max_value=80, value=25)
    height_cm = st.number_input('Altura (cm)', min_value=100, max_value=220, value=170)
    weight_kg = st.number_input('Peso (kg)', min_value=30, max_value=200, value=70)
    heart_rate = st.number_input('Frecuencia cardíaca (bpm)', min_value=40, max_value=120, value=70)
    blood_pressure = st.number_input('Presión arterial (mmHg)', min_value=80, max_value=200, value=120)
    sleep_hours = st.number_input('Horas de sueño', min_value=0.0, max_value=12.0, value=7.0)
    nutrition_quality = st.slider('Calidad nutricional (0-10)', 0.0, 10.0, 5.0)
    activity_index = st.slider('Índice de actividad (1-5)', 1.0, 5.0, 3.0)
    smokes = st.selectbox('¿Fumas?', ['No', 'Sí'])
    gender = st.selectbox('Género', ['M', 'F'])

    smokes_bin = 1 if smokes == 'Sí' else 0
    gender_bin = 1 if gender == 'F' else 0

    return pd.DataFrame({
        'age': [age],
        'height_cm': [height_cm],
        'weight_kg': [weight_kg],
        'heart_rate': [heart_rate],
        'blood_pressure': [blood_pressure],
        'sleep_hours': [sleep_hours],
        'nutrition_quality': [nutrition_quality],
        'activity_index': [activity_index],
        'smokes': [smokes_bin],
        'gender': [gender_bin]
    })

# Obtener entrada del usuario
entrada = user_input()

# Predicción
pred = modelo.predict(entrada)[0]
estado = "En forma" if pred == 1 else "No en forma"

# Mostrar resultado
st.subheader("Resultado")
st.write(f"Predicción: **{estado}**")