# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Jfs_A8Bm0irOXuCRyI16uKMmufp5W_l
"""

import pandas as pd
import numpy as np
import streamlit as st

st.write("¿Estás en forma?")
st.image("fit.jpg", caption="Clasificación de condición física", use_container_width=True)
st.header("Ingresa tus datos")

def load_data():
    df = pd.read_csv('Fitness_Classification.csv', encoding='latin-1')
    # Limpiar columna 'fuma'
    df['fuma'] = df['fuma'].astype(str).str.lower()
    df['fuma'] = df['fuma'].map({'0': 0, '1': 1, 'no': 0, 'sí': 1, 'si': 1}).fillna(0)

    le = LabelEncoder()
    df['género'] = le.fit_transform(df['género'])
    df = df.dropna(subset=['está_en_forma'])
    for col in df.select_dtypes(include=[np.number]).columns:
        df[col] = df[col].fillna(df[col].median())
    return df, le

datos, le_genero = load_data()

X = datos.drop(columns=['está_en_forma'])
y = datos['está_en_forma']

modelo = DecisionTreeClassifier(random_state=1613318)
modelo.fit(X, y)

def user_input():
    edad = st.number_input('Edad', min_value=15, max_value=80, value=25)
    altura_cm = st.number_input('Altura (cm)', min_value=100, max_value=220, value=170)
    peso_kg = st.number_input('Peso (kg)', min_value=30, max_value=200, value=70)
    frecuencia_cardiaca = st.number_input('Frecuencia cardíaca (bpm)', min_value=40, max_value=120, value=70)
    presión_arterial = st.number_input('Presión arterial (mmHg)', min_value=80, max_value=200, value=120)
    horas_sueño = st.number_input('Horas de sueño', min_value=0.0, max_value=12.0, value=7.0)
    calidad_nutricional = st.slider('Calidad nutricional (0-10)', 0.0, 10.0, 5.0)
    índice_actividad = st.slider('Índice de actividad (1-5)', 1.0, 5.0, 3.0)
    fuma = st.selectbox('¿Fumas?', ['No', 'Sí'])
    género = st.selectbox('Género', ['M', 'F'])

    fuma_bin = 1 if fuma == 'Sí' else 0
    género_bin = 1 if género == 'F' else 0

    return pd.DataFrame({
        'edad': [edad],
        'altura_cm': [altura_cm],
        'peso_kg': [peso_kg],
        'frecuencia_cardiaca': [frecuencia_cardiaca],
        'presión_arterial': [presión_arterial],
        'horas_sueño': [horas_sueño],
        'calidad_nutricional': [calidad_nutricional],
        'índice_actividad': [índice_actividad],
        'fuma': [fuma_bin],
        'género': [género_bin]
    })

entrada = user_input()

pred = modelo.predict(entrada)[0]
estado = "En forma" if pred == 1 else "No en forma"

st.subheader("Resultado")
st.write(f"Predicción: **{estado}**")